name: DISABLED legacy deploy (site/)

on:
  # Disabled: only manual runs permitted to avoid conflicting with Astro deploy
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Legacy workflow disabled. Use deploy.yml (Astro) instead."
