name: Indicator Tests

on:
  push:
    paths:
      - 'tools/python_indicator_clone/**'
      - '.github/workflows/indicator-tests.yml'
  pull_request:
    paths:
      - 'tools/python_indicator_clone/**'
      - '.github/workflows/indicator-tests.yml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12' ]
        ccxt: ['yes','no']
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/python_indicator_clone
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          if [ "${{ matrix.ccxt }}" = "no" ]; then
            pip uninstall -y ccxt || true
          fi
      - name: Provider availability
        run: |
          python -c "import importlib.util; mods=['ccxt','yfinance','tenacity']; [print(f'{m}:', 'present' if importlib.util.find_spec(m) else 'missing') for m in mods]"
      - name: Run deterministic core tests
        run: pytest -q tests/test_resample_math.py tests/test_resample_tail_option.py tests/test_gap_detector.py tests/test_fallback_polygon.py tests/test_fallback_equity_router.py
      - name: Run network tests (if deps present)
        if: matrix.ccxt == 'yes'
        run: pytest -q -m "network"
      - name: Coverage (fail under threshold)
        run: pytest -q --cov=ql_indicator --cov-report=term-missing --cov-fail-under=85
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}-ccxt-${{ matrix.ccxt }}
          path: tools/python_indicator_clone
